#!/bin/bash
export FZF_DEFAULT_OPTS='--height 60% --layout reverse --border'
export FZF_COMPLETION_TRIGGER=''
export FZF_COMPLETION_OPTS='--border --info=inline'

_fzf_compgen_path() {
    fd -u --follow -d1 . "$1"
}

_fzf_compgen_dir() {
    fd -u --follow -td -d1 . "$1"
}

_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
	cd)		fzf -0 -1 "$@" --preview 'exa -TL 1 --icons --git-ignore {}' ;;
	vim|ln|mv|cp|rm)fzf -0 -1 "$@" --preview 'if [ -d {} ]; then exa -TL 1 --icons --git-ignore {}; else bat --color always --style numbers,grid {}; fi' ;;
	ssh)		fzf -0 -1 "$@" --preview 'dig {}' ;;
	export|unset)	fzf -0 -1 "$@" --preview "eval 'echo \$'{} " ;;
	*)		fzf -0 -1 "$@" ;;
    esac
}
